=== TUM-I5/MolSim/input/XMLFormat.xsd
<?xml version="1.0"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <!-- Support Data Structures -->

    <xsd:complexType name="dvector_t">
        <xsd:attribute name="X" type="xsd:double" use="required"/>
        <xsd:attribute name="Y" type="xsd:double" use="required"/>
        <xsd:attribute name="Z" type="xsd:double" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="ivector_t">
        <xsd:attribute name="X" type="xsd:nonNegativeInteger" use="required"/>
        <xsd:attribute name="Y" type="xsd:nonNegativeInteger" use="required"/>
        <xsd:attribute name="Z" type="xsd:nonNegativeInteger" use="required"/>
    </xsd:complexType>

    <xsd:simpleType name="nonNegativeDouble_t">
        <xsd:restriction base="xsd:double">
            <xsd:minInclusive value="0"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="positiveDouble_t">
        <xsd:restriction base="xsd:double">
            <xsd:minExclusive value="0"/>
        </xsd:restriction>
    </xsd:simpleType>


    <xsd:complexType name="posDVector_t">
        <xsd:attribute name="X" type="positiveDouble_t" use="required"/>
        <xsd:attribute name="Y" type="positiveDouble_t" use="required"/>
        <xsd:attribute name="Z" type="positiveDouble_t" use="required"/>
    </xsd:complexType>


    <!-- I/O -->

    <!-- NOT REQUIRED

    <xsd:complexType name="input_t">
        <xsd:attribute name="path" type="xsd:string" use="required"/>
    </xsd:complexType>
    -->

    <xsd:complexType name="output_t">
        <xsd:attribute name="FolderPath" type="xsd:string"/>
        <xsd:attribute name="OutputFileName" type="xsd:string"/>
    </xsd:complexType>

    <xsd:simpleType name="outputWriter_t">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Vtk"/>
            <xsd:enumeration value="Xyz"/>
        </xsd:restriction>
    </xsd:simpleType>

    <!-- Force Calculation -->

    <xsd:complexType name="gravity_t"/>

    <xsd:complexType name="lennardJones_t">
        <xsd:attribute name="Epsilon" type="xsd:double"/>
        <xsd:attribute name="Sigma" type="nonNegativeDouble_t"/>
    </xsd:complexType>

    <xsd:complexType name="lennardJonesCell_t">
        <xsd:attribute name="Epsilon" type="xsd:double"/>
        <xsd:attribute name="Sigma" type="nonNegativeDouble_t"/>
    </xsd:complexType>

    <xsd:complexType name="lennardJonesOMP_t">
        <xsd:attribute name="Epsilon" type="xsd:double"/>
        <xsd:attribute name="Sigma" type="nonNegativeDouble_t"/>
    </xsd:complexType>

    <xsd:complexType name="forceCalculation_t">
        <xsd:choice>
            <xsd:element name="Gravity" type="gravity_t"/>
            <xsd:element name="LennardJones" type="lennardJones_t"/>
            <xsd:element name="LennardJonesCell" type="lennardJonesCell_t"/>
            <xsd:element name="LennardJonesOMP" type="lennardJonesOMP_t"/>
        </xsd:choice>
    </xsd:complexType>

    <!-- Position Calculation -->

    <xsd:simpleType name="positionCalculation_t">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="StoermerVelvet"/>
            <xsd:enumeration value="StoermerVelvetOMP"/>
        </xsd:restriction>
    </xsd:simpleType>

    <!-- Velocity Calculation -->

    <xsd:simpleType name="velocityCalculation_t">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="StoermerVelvet"/>
            <xsd:enumeration value="StoermerVelvetOMP"/>
        </xsd:restriction>
    </xsd:simpleType>

    <!-- Boundary -->

    <xsd:simpleType name="boundaryBehavior_t">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Outflow"/>
            <xsd:enumeration value="Reflecting"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="boundaries_t">
        <xsd:sequence>
            <xsd:element name="BoxSize" type="posDVector_t"/>
            <xsd:element name="Front" type="boundaryBehavior_t"/>
            <xsd:element name="Rear" type="boundaryBehavior_t"/>
            <xsd:element name="Left" type="boundaryBehavior_t"/>
            <xsd:element name="Right" type="boundaryBehavior_t"/>
            <xsd:element name="Top" type="boundaryBehavior_t"/>
            <xsd:element name="Bottom" type="boundaryBehavior_t"/>
        </xsd:sequence>
    </xsd:complexType>

    <!-- Simulation Types -->

    <xsd:complexType name="linkedCell_t">
        <xsd:sequence>
            <xsd:element name="BoundaryBox" type="boundaries_t"/>
            <xsd:element name="CutoffRadius" type="nonNegativeDouble_t"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="naive_t"/>

    <xsd:complexType name="simulationStrategy_t">
        <xsd:choice>
            <xsd:element name="LinkedCell" type="linkedCell_t"/>
            <xsd:element name="Naive" type="naive_t"/>
        </xsd:choice>
    </xsd:complexType>

    <!-- Misc -->

    <xsd:simpleType name="logLevel_t">
        <xsd:restriction base="xsd:nonNegativeInteger">
            <xsd:minInclusive value="0"/>
            <xsd:maxInclusive value="6"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="fileBenchmark_t"/>

    <xsd:complexType name="defaultBenchmark_t">
        <xsd:attribute name="MaximumBodySize" type="xsd:nonNegativeInteger"/>
    </xsd:complexType>

    <xsd:complexType name="benchmarkType_t">
        <xsd:choice>
            <xsd:element name="FileBenchmark" type="fileBenchmark_t"/>
            <xsd:element name="DefaultBenchmark" type="defaultBenchmark_t"/>
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="benchmark_t">
        <xsd:sequence>
            <xsd:element name="BenchmarkType" type="benchmarkType_t"/>
            <xsd:element name="IterationCount" type="xsd:positiveInteger" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="dimension_t">
        <xsd:restriction base="xsd:positiveInteger">
            <xsd:minInclusive value="2"/>
            <xsd:maxInclusive value="3"/>
        </xsd:restriction>
    </xsd:simpleType>

    <!-- Shapes -->

    <xsd:complexType name="particle_t">
        <xsd:sequence>
            <xsd:element name="Position" type="dvector_t"/>
            <xsd:element name="Velocity" type="dvector_t"/>
        </xsd:sequence>
        <xsd:attribute name="Mass" type="xsd:double" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="cuboid_t">
        <xsd:sequence>
            <xsd:element name="Position" type="dvector_t"/>
            <xsd:element name="Velocity" type="dvector_t"/>
            <xsd:element name="Dimensions" type="ivector_t"/>
        </xsd:sequence>
        <xsd:attribute name="Spacing" type="xsd:double" use="required"/>
        <xsd:attribute name="Mass" type="xsd:double" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="sphere_t">
        <xsd:sequence>
            <xsd:element name="Position" type="dvector_t"/>
            <xsd:element name="Velocity" type="dvector_t"/>
        </xsd:sequence>
        <xsd:attribute name="Radius" type="xsd:positiveInteger" use="required"/>
        <xsd:attribute name="Spacing" type="xsd:double" use="required"/>
        <xsd:attribute name="Mass" type="xsd:double" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="shape_t">
        <xsd:choice>
            <xsd:element name="Particle" type="particle_t"/>
            <xsd:element name="Cuboid" type="cuboid_t"/>
            <xsd:element name="Sphere" type="sphere_t"/>
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="shapeList_t">
        <xsd:sequence>
            <xsd:element name="Shape" type="shape_t" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <!-- Simulation -->

    <xsd:complexType name="simulation_t">
        <xsd:sequence>
            <!-- IO -->
            <xsd:element name="OutputFile" type="output_t" minOccurs="0"/>
            <!-- Calculation Decisions -->
            <xsd:element name="StartTime" type="xsd:double" minOccurs="0"/>
            <xsd:element name="EndTime" type="xsd:double" minOccurs="0"/>
            <xsd:element name="TimeStepSize" type="nonNegativeDouble_t" minOccurs="0"/>
            <xsd:element name="ForceCalculation" type="forceCalculation_t"/>
            <xsd:element name="PositionCalculation" type="positionCalculation_t" minOccurs="0"/>
            <xsd:element name="VelocityCalculation" type="velocityCalculation_t" minOccurs="0"/>
            <xsd:element name="AverageBrownianMotion" type="nonNegativeDouble_t" minOccurs="0"/>
            <xsd:element name="SimulationStrategy" type="simulationStrategy_t"/>
            <xsd:element name="Dimensions" type="dimension_t" minOccurs="0"/>
            <!-- Misc -->
            <xsd:element name="LogLevel" type="logLevel_t" minOccurs="0"/>
            <xsd:element name="Benchmark" type="benchmark_t" minOccurs="0"/>
            <!-- Particles -->
            <xsd:element name="ShapeList" type="shapeList_t"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:element name="Simulation" type="simulation_t"/>

</xsd:schema>

=== TUM-I5/MolSim/resources/tests/tooFewVectorElements.xml
<?xml version="1.0" encoding="UTF-8"?>
<Simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="XMLFormat.xsd">
    <ForceCalculation>
        <Gravity/>
    </ForceCalculation>
    <SimulationStrategy>
        <Naive/>
    </SimulationStrategy>
    <FileType>
        <Input>
            <ShapeList>
                <Shape>
                    <Particle Mass="1.0">
                        <Position X="0" Y="0"/>
                        <Velocity X="0" Y="0" Z="0"/>
                    </Particle>
                </Shape>
            </ShapeList>
        </Input>
    </FileType>
</Simulation>

=== TUM-I5/MolSim/input/ws3.xml
<Simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="XMLFormat.xsd">
    <OutputFile OutputFileName="ws3"/>
    <EndTime>10.0</EndTime>
    <TimeStepSize>0.00005</TimeStepSize>
    <ForceCalculation>
        <LennardJones Epsilon="5.0" Sigma="1.0"/>
    </ForceCalculation>
    <SimulationStrategy>
        <LinkedCell>
            <BoundaryBox>
                <BoxSize x="120.0" y="50.0" z="1.0"/>
                <Front>"Reflection"</Front>
                <Rear>"Reflection</Rear>
                <Left>"Reflection"</Left>
                <Right>"Reflection"</Right>
                <Top>"Reflection"</Top>
                <Bottom>"Reflection"</Bottom>
            </BoundaryBox>
            <CutoffRadius>3.0</CutoffRadius>
        </LinkedCell>
    </SimulationStrategy>
    <Dimensions>2</Dimensions>
    <ShapeList>
        <Shape>
            <Sphere Radius="15.0" Spacing="1.1225" Mass="1.0">
                <Position x="60.0" y="25.0" z="0.0"/>
                <Velocity x="0.0" y="-10.0" z="0.0"/>
            </Sphere>
        </Shape>
    </ShapeList>
</Simulation>

=== TUM-I5/MolSim/input/thermo.xml
<?xml version="1.0" encoding="UTF-8"?>
<Simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../input/XMLFormat.xsd">
    <EndTime>25.0</EndTime>
    <TimeStepSize>0.0005</TimeStepSize>
    <ForceCalculation>
        <LennardJonesGravity G_Grav="-12.44" Epsilon="1.0" Sigma="1.0"/>
    </ForceCalculation>
    <AverageBrownianMotion>0.0</AverageBrownianMotion>
    <SimulationStrategy>
        <LinkedCell>
            <BoundaryBox>
                <BoxSize X="63" Y="36" Z="1"/>
                <Front>Reflecting</Front>
                <Rear>Reflecting</Rear>
                <Left>Reflecting</Left>
                <Right>Reflecting</Right>
                <Top>Reflecting</Top>
                <Bottom>Reflecting</Bottom>
            </BoundaryBox>
            <CutoffRadius>2.5</CutoffRadius>
        </LinkedCell>
    </SimulationStrategy>
    <Dimensions>2</Dimensions>
    <Thermostat>
        <T_Init>40 </T_Init>
        <N_Term>1000</N_Term>
    </Thermostat>
    <FileType>
        <Input>
            <ShapeList>
                <Shape>
                    <Cuboid Spacing="1.2" Mass="1.0" Epsilon="1.0" Sigma="1.0">
                        <Position X="0.6" Y="2.0" Z="0.0" />
                        <Velocity X="0.0" Y="0.0" Z="0.0"/>
                        <Dimensions X="50" Y="14" Z="1"/>
                    </Cuboid>
                </Shape>
                <Shape>
                    <Cuboid Spacing="1.2" Mass="2.0" Sigma="0.9412" Epsilon="1.0">
                        <Position X="0.6" Y="19.0" Z="0.0"/>
                        <Velocity X="0.0" Y="0" Z="0.0"/>
                        <Dimensions X="50" Y="14" Z="1"/>
                    </Cuboid>
                </Shape>
            </ShapeList>
        </Input>
    </FileType>
</Simulation>

=== TUM-I5/MolSim/input/perf.xml
<?xml version="1.0" encoding="UTF-8"?>
<Simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../input/XMLFormat.xsd">
    <EndTime>5.0</EndTime>
    <TimeStepSize>0.0005</TimeStepSize>
    <ForceCalculation>
        <LennardJonesCell Epsilon="1.0" Sigma="1.0"/>
    </ForceCalculation>
    <AverageBrownianMotion>0.01</AverageBrownianMotion>
    <SimulationStrategy>
        <LinkedCell>
            <BoundaryBox>
                <BoxSize X="12.0" Y="12.0" Z="102.0"/>
                <Front>Periodic</Front>
                <Rear>Periodic</Rear>
                <Left>Periodic</Left>
                <Right>Periodic</Right>
                <Top>Reflecting</Top>
                <Bottom>Reflecting</Bottom>
            </BoundaryBox>
            <CutoffRadius>2.5</CutoffRadius>
        </LinkedCell>
    </SimulationStrategy>
    <Dimensions>3</Dimensions>
    <Thermostat>
        <T_Init>40</T_Init>
        <N_Term>1000</N_Term>
    </Thermostat>
    <FileType>
        <Input>
            <ShapeList>
                <Shape>
                    <Cuboid Spacing="1.0" Mass="1.0">
                        <Position X="1.0" Y="1.0" Z="1.0"/>
                        <Velocity X="0.0" Y="0.0" Z="0.0"/>
                        <Dimensions X="10" Y="10" Z="100"/>
                    </Cuboid>
                </Shape>
            </ShapeList>
        </Input>
    </FileType>
</Simulation>

=== TUM-I5/MolSim/input/periodic.xml
<?xml version="1.0" encoding="UTF-8"?>
<Simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../input/XMLFormat.xsd">
    <OutputFile OutputFileName="periodic"/>
    <EndTime>25.0</EndTime>
    <TimeStepSize>0.0005</TimeStepSize>
    <ForceCalculation>
        <LennardJonesCell Epsilon="1.0" Sigma="1.0"/>
    </ForceCalculation>
    <AverageBrownianMotion>0.01</AverageBrownianMotion>
    <SimulationStrategy>
        <LinkedCell>
            <BoundaryBox>
                <BoxSize X="80.0" Y="50.0" Z="1.0"/>
                <Front>Reflecting</Front>
                <Rear>Reflecting</Rear>
                <Left>Periodic</Left>
                <Right>Periodic</Right>
                <Top>Reflecting</Top>
                <Bottom>Reflecting</Bottom>
            </BoundaryBox>
            <CutoffRadius>2.5</CutoffRadius>
        </LinkedCell>
    </SimulationStrategy>
    <Dimensions>2</Dimensions>
    <FileType>
        <Input>
            <ShapeList>
                <Shape>
                    <Sphere Radius="15" Spacing="1.1225" Mass="1.0">
                        <Position X="60.0" Y="25.0" Z="0.0"/>
                        <Velocity X="20.0" Y="0.0" Z="0.0"/>
                    </Sphere>
                </Shape>
                <Shape>
                    <Cuboid Spacing="1.0" Mass="2.0">
                        <Position X="1.0" Y="1.0" Z="0.0"/>
                        <Velocity X="0.0" Y="0.0" Z="0.0"/>
                        <Dimensions X="40" Y="40" Z="1"/>
                    </Cuboid>
                </Shape>
            </ShapeList>
        </Input>
    </FileType>
</Simulation>

=== TUM-I5/MolSim/resources/tests/XMLReaderInput.xml
<?xml version="1.0" encoding="UTF-8"?>
<Simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="XMLFormat.xsd">
    <OutputFile FolderPath="tmpPath" OutputFileName="tmpOutput"/>
    <StartTime>5.0</StartTime>
    <EndTime>10.0</EndTime>
    <TimeStepSize>2.0</TimeStepSize>
    <ForceCalculation>
        <LennardJonesCell Epsilon="5.0" Sigma="1.0"/>
    </ForceCalculation>
    <PositionCalculation>StoermerVelvetOMP</PositionCalculation>
    <VelocityCalculation>StoermerVelvetOMP</VelocityCalculation>
    <AverageBrownianMotion>5.0</AverageBrownianMotion>
    <SimulationStrategy>
        <LinkedCell>
            <BoundaryBox>
                <BoxSize X="120.0" Y="50.0" Z="10.0"/>
                <Front>Outflow</Front>
                <Rear>Outflow</Rear>
                <Left>Reflecting</Left>
                <Right>Reflecting</Right>
                <Top>Reflecting</Top>
                <Bottom>Reflecting</Bottom>
            </BoundaryBox>
            <CutoffRadius>3.0</CutoffRadius>
        </LinkedCell>
    </SimulationStrategy>
    <Dimensions>3</Dimensions>
    <Thermostat>
        <T_Init>50.0</T_Init>
        <N_Term>987</N_Term>
        <T_Target>30.0</T_Target>
        <Delta_T>576.3</Delta_T>
    </Thermostat>
    <LogLevel>5</LogLevel>
    <Benchmark>
        <BenchmarkType>
            <DefaultBenchmark MaximumBodySize="100"/>
        </BenchmarkType>
        <IterationCount>10000</IterationCount>
    </Benchmark>
    <EnableCheckpointing>1</EnableCheckpointing>
    <FileType>
        <Input>
            <ShapeList>
                <Shape>
                    <Sphere Radius="15" Spacing="1.1225" Mass="1.0">
                        <Position X="60.0" Y="25.0" Z="0.0"/>
                        <Velocity X="0.0" Y="-10.0" Z="0.0"/>
                    </Sphere>
                </Shape>
            </ShapeList>
        </Input>
    </FileType>
</Simulation>

=== TUM-I5/MolSim/input/fallingDrop1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="XMLFormat.xsd">
    <OutputFile OutputFileName="fallingDrop1"/>
    <EndTime>40.0</EndTime>
    <TimeStepSize>0.0005</TimeStepSize>
    <ForceCalculation>
        <LennardJonesGravity G_Grav="-12.44" Epsilon="1.0" Sigma="1.0"/>
    </ForceCalculation>
    <SimulationStrategy>
        <LinkedCell>
            <BoundaryBox>
                <BoxSize X="303.0" Y="180.0" Z="1.0"/>
                <Front>Reflecting</Front>
                <Rear>Reflecting</Rear>
                <Left>Reflecting</Left>
                <Right>Reflecting</Right>
                <Top>Reflecting</Top>
                <Bottom>Reflecting</Bottom>
            </BoundaryBox>
            <CutoffRadius>3.0</CutoffRadius>
        </LinkedCell>
    </SimulationStrategy>
    <Dimensions>2</Dimensions>
    <FileType>
        <Input>
            <ShapeList>
                <Shape>
                    <Sphere Radius="20" Spacing="1.2" Mass="1.0">
                        <Position X="150.0" Y="150.0" Z="0.0"/>
                        <Velocity X="0.0" Y="0.0" Z="0.0"/>
                    </Sphere>
                </Shape>
            </ShapeList>
        </Input>
    </FileType>
</Simulation>

=== TUM-I5/MolSim/input/large_rti.xml
<?xml version="1.0" encoding="UTF-8"?>
<Simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="XMLFormat.xsd">
    <OutputFile OutputFileName="large_rti"/>
    <EndTime>50.0</EndTime>
    <TimeStepSize>0.0005</TimeStepSize>
    <ForceCalculation>
        <LennardJonesGravity G_Grav="-12.44" Epsilon="1.0" Sigma="1.0"/>
    </ForceCalculation>
    <AverageBrownianMotion>0.0</AverageBrownianMotion>
    <SimulationStrategy>
        <LinkedCell>
            <BoundaryBox>
                <BoxSize X="300.0" Y="54.0" Z="1.0"/>
                <Front>Reflecting</Front>
                <Rear>Reflecting</Rear>
                <Left>Periodic</Left>
                <Right>Periodic</Right>
                <Top>Reflecting</Top>
                <Bottom>Reflecting</Bottom>
            </BoundaryBox>
            <CutoffRadius>3.0</CutoffRadius>
        </LinkedCell>
    </SimulationStrategy>
    <Dimensions>2</Dimensions>
    <Thermostat>
        <T_Init>40.0</T_Init>
        <N_Term>1000</N_Term>
    </Thermostat>
    <FileType>
        <Input>
            <ShapeList>
                <Shape>
                    <Cuboid Spacing="1.2" Mass="1.0" Epsilon="1.0" Sigma="1.2">
                        <Position X="0.6" Y="2.0" Z="0.0"/>
                        <Velocity X="0.0" Y="0.0" Z="0.0"/>
                        <Dimensions X="250" Y="20" Z="1"/>
                    </Cuboid>
                </Shape>
                <Shape>
                    <Cuboid Spacing="1.2" Mass="2.0" Epsilon="1.0" Sigma="1.1">
                        <Position X="0.6" Y="27.0" Z="0.0"/>
                        <Velocity X="0.0" Y="0.0" Z="0.0"/>
                        <Dimensions X="250" Y="20" Z="1"/>
                    </Cuboid>
                </Shape>
            </ShapeList>
        </Input>
    </FileType>
</Simulation>
